name: .NET Build

on:
  push:
      paths-ignore:
      - '.github/*'
      - '.github/*_TEMPLATE/**'
      - '*.md'
  pull_request:
      paths-ignore:
      - '.github/*'
      - '.github/*_TEMPLATE/**'
      - '*.md'

jobs:
  build:
    name: .NET on ${{ matrix.runs-on }} (${{ matrix.configuration }})
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on: [windows-latest]
        configuration: [Release,Debug]
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Publish
      run: dotnet publish -c ${{ matrix.configuration }} --property:PublishDir=../artifacts

    - name: Upload artifact (Applications)
      uses: actions/upload-artifact@v3
      with:
        name: TarkovServerApplications
        path: Applications\artifacts\
        if-no-files-found: error

    - name: Upload artifact (Plugins)
      uses: actions/upload-artifact@v3
      with:
        name: TarkovServerPlugins
        path: Plugins\artifacts\
        if-no-files-found: error
        
    - name: Upload artifact (Core/Lib)
      uses: actions/upload-artifact@v3
      with:
        name: TarkovServerLib
        path: artifacts\
        if-no-files-found: error
